# Generated by Django 5.1 on 2024-08-23 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_student_birthday_alter_studentjobs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='studentjobs',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
