# Generated by Django 5.1 on 2024-08-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_student_birthday_alter_studentjobs_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentjobs',
            options={'ordering': ['-date']},
        ),
    ]
