# Generated by Django 5.1 on 2024-08-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_availablejobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='availablejobs',
            field=models.ManyToManyField(to='my_app.availablejobs'),
        ),
    ]
